user_register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: POST

user_login:
    path: /api/login/2fa
    controller: App\Controller\SecurityController::loginn
    methods: POST

api_books_get:
    path: /api/books
    controller: App\Controller\BookController::getBooks
    methods: GET

api_books_post:
    path: /api/books/post
    controller: App\Controller\BookController::createBook
    methods: POST

api_books_delete:
    path: /api/books/{id}/delete
    controller: App\Controller\BookController::deleteBook
    methods: DELETE
    
api_books_get_one:
    path: /api/books/{id}
    controller: App\Controller\BookController::getBook
    methods: GET
 
api_books_put:
    path: /api/books/{id}/put
    controller: App\Controller\BookController::updateBook
    methods: PUT
 
api_user_get:
    path: /api/users/{id}
    controller: App\Controller\UserController::getUserinfo
    methods: GET

api_users_get_all:
    path: /api/users
    controller: App\Controller\UserController::getAllUsers
    methods: GET

api_user_update:
    path: /api/users/{id}/put
    controller: App\Controller\UserController::updateUser
    methods: [PUT, PATCH]

api_user_delete:
    path: /api/users/{id}/delete
    controller: App\Controller\UserController::deleteUser
    methods: DELETE

api_user:
    path: /api/user
    controller: App\Controller\UserController::getUserInfos
    methods: GET

api_books_count:
    path: /api/count/books
    controller: App\Controller\BookController::countBooks
    methods: GET

api_users_count:
    path: /api/count/users
    controller: App\Controller\UserController::countUsers
    methods: GET
    
api_users_search:
    path: /api/usersearch
    controller: App\Controller\UserController::searchUsers
    methods: GET

api_books_search:
    path: /api/booksearch
    controller: App\Controller\BookController::searchBooks
    methods: GET

api_borrowings_index:
    path: /api/borrowings
    controller: App\Controller\BorrowingsController::getallBorrowings
    methods: GET

api_borrowings_by_book:
    path: /api/borrowings/book/{id}
    controller: App\Controller\BorrowingsController::getBorrowingsByBook
    methods: GET

api_borrowings_by_user:
    path: /api/borrowings/user/{id}
    controller: App\Controller\BorrowingsController::getBorrowingsByUser
    methods: GET

api_borrowings_by_user_add:
    path: /api/readerdetails/{id}/borrow
    controller: App\Controller\BorrowingsController::addBorrowing
    methods: POST
    
api_update_prolongation:
    path: /api/borrowings/{id}/prolongation
    controller: App\Controller\BorrowingsController::updateProlongation
    methods: POST
    
api_date_update:
    path: /api/borrowings/{id}/realreturndate
    controller: App\Controller\BorrowingsController::updateRealReturnDate
    methods: POST

api_borrowings_by_user_and_status:
    path: /api/borrowingsbystatus/user/{id}
    controller: App\Controller\BorrowingsController::getBorrowingsByUserByStatus
    methods: GET

api_borrowings_by_user_5:
    path: /api/borrowings/5/user/{id}
    controller: App\Controller\BorrowingsController::getBorrowings5ByUser
    methods: GET
    
api_getFilteredBorrowings:
    path: /api/filteredBorrowings
    controller: App\Controller\BorrowingsController::getFilteredBorrowings
    methods: GET

api_fivebooks:
    path: /api/fivebooks
    controller: App\Controller\BookController::getBooksFive
    methods: GET

api_fiveusers:
    path: /api/fiveusers
    controller: App\Controller\UserController::getFiveUsers
    methods: GET

api_borrowingsmonthly:
    path: /api/borrowingsmonthly
    controller: App\Controller\BorrowingsController::getMonthlyBorrowings
    methods: GET

api_borrowingsmonthly_five:
    path: /api/filteredBorrowingsfive
    controller: App\Controller\BorrowingsController::getFilteredBorrowingsfive
    methods: GET

api_usersmonthly:
    path: /api/usersmonthly
    controller: App\Controller\UserController::getMonthlyUsers
    methods: GET
